# prowl-github-app configuration. Place in default branch

version: '0.1.0'

targets:
  - id: markdown
    stalk:
      paths:
        - "**/*.md"
      base: master
    pounce:
      reviewers: []

  - id: markdown
    stalk:
      paths:
        - "dry/**/*"
      base: master
    pounce:
      reviewers: []
    dry_run: true

